# Generated by Django 3.1.7 on 2021-05-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='Media key')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя комментатора')),
                ('comment', models.TextField(verbose_name='Отзыв')),
            ],
        ),
        migrations.CreateModel(
            name='TextObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='Id текстовой записи')),
                ('value', models.TextField(verbose_name='Значение текстовой записи')),
            ],
        ),
    ]
