# Generated by Django 3.1.7 on 2021-05-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaobject',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='textobject',
            name='key',
            field=models.CharField(max_length=50, unique=True, verbose_name='Id текстовой записи'),
        ),
    ]
