# Generated by Django 3.1.7 on 2021-05-18 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название стастьи')),
                ('annotation', models.TextField(verbose_name='Аннотация (краткое описание статьи)')),
            ],
        ),
        migrations.CreateModel(
            name='PostItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200, verbose_name='Подзаголовок')),
                ('content', models.TextField(verbose_name='Текст абзаца')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.post', verbose_name='Статья')),
            ],
        ),
        migrations.CreateModel(
            name='PostItemMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('post_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.postitem', verbose_name='Абзац')),
            ],
        ),
    ]
