# Generated by Django 3.1.7 on 2021-05-18 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.FileField(default=2, upload_to='', verbose_name='Обложка статьи'),
            preserve_default=False,
        ),
    ]
