# Generated by Django 3.1.7 on 2021-05-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20210518_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitemmedia',
            name='media_type',
            field=models.CharField(choices=[('video', 'video'), ('image', 'image')], default='image', max_length=50, verbose_name='Тип файла'),
            preserve_default=False,
        ),
    ]
